### ISSUE TITLE
Server crashes on every start

### ISSUE THREAD

**Issue by RainOfPain125** [CivClassic/AnsibleSetup#251]
https://www.toptal.com/developers/hastebin/uyuqesukec.yaml

I added all the plugins. Server would not start because namelayers will close the server if not given access to an SQL.

I gave namelayers access to an SQL and the server successfully works.

I then gave the rest of the plugins that needed a database, their own database, and it no longer starts.

**Comment by Maxopoly** [comment]
The error seems to be related to the configuration of CivModCore. Could you pastebin that config (censor the password)?

**Comment by Protonull** [comment]
Looking at the stacktrace, [this](https://github.com/CivClassic/CivModCore/blob/13a52d5bd35efb6bc7cb1aff1989a3aaedb5d880/src/main/java/vg/civcraft/mc/civmodcore/dao/DatabaseCredentials.java#L103) is the offending line of code. I'm therefore guessing that @RainOfPain125's config looks something along the lines of:
```yaml
database:
  ==: vg.civcraft.mc.civmodcore.dao.ManagedDatasource
  plugin: CivModCore
  user: username
  password: 1234 # HERE'S THE PROBLEM
  host: localhost
  port: 3306
  database: minecraft
  poolsize: 5
  connection_timeout: 10000
  idle_timeout: 600000
  max_lifetime: 7200000
```
ie, that the password is being parsed as a number, so it fails when the parser attempts to cast it to a String. The quick fix is to encapsulate the password inside quotations, like so: `password: "1234"`, but a systematic solution could be update the parsing method itself to use `String.valueOf(Object)` as a parser.
